# Stage 1: Build Stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json first to install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the app (including next.config.js)
COPY . .

RUN npm run build

# Stage 2: Final Stage
FROM node:18-alpine

WORKDIR /app

# Copy built files from builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules


EXPOSE 3000

CMD ["npm", "run", "start"]
